import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

export function exportToCsv(filename: string, headers: string[], rows: (string | number | null | undefined)[][]) {
  const csv = [headers, ...rows]
    .map((r) => r.map((c) => `"${String(c ?? '').replace(/"/g, '""')}"`).join(','))
    .join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToExcel(
  filename: string,
  sheetName: string,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  title: string,
  userName: string,
  role: string
) {
  const wb = XLSX.utils.book_new();
  const dateStr = format(new Date(), 'PPP p');
  const roleDisplay = role.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

  const exportData: any[][] = [
    ['Two Brothers Food Complex P.L.C'],
    ['2BF Factory ERP — Export Report'],
    [],
    ['Report Title', title],
    ['Generated Date', dateStr],
    ['Generated By', `${userName} (${roleDisplay})`],
    [],
    headers,
    ...rows
  ];

  const ws = XLSX.utils.aoa_to_sheet(exportData);
  
  // Set reasonable column widths
  const colWidths = headers.map(() => ({ wch: 20 }));
  ws['!cols'] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, sheetName.substring(0, 31)); // sheetName max length is 31
  XLSX.writeFile(wb, filename);
}

export function exportToPDF(
  filename: string,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  title: string,
  userName: string,
  role: string
) {
  // Use landscape if there are many columns
  const orientation = headers.length > 6 ? 'landscape' : 'portrait';
  const doc = new jsPDF(orientation);
  const dateStr = format(new Date(), 'PPP p');
  const roleDisplay = role.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

  // ── Header ──
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Two Brothers Food Complex P.L.C', 14, 20);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50);
  doc.text(title, 14, 28);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${dateStr}`, 14, 38);
  doc.text(`By: ${userName} (${roleDisplay})`, 14, 44);

  // ── Table ──
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: 55,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // ── Footer ──
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.setFont('helvetica', 'normal');
    doc.text('Two Brothers Food Complex P.L.C © 2026 — 2BF Factory ERP — Confidential', 14, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
  }

  doc.save(filename);
}
