import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

export function exportToCsv(filename: string, headers: string[], rows: (string | number | null | undefined)[][]) {
  const csv = [headers, ...rows]
    .map((r) => r.map((c) => `"${String(c ?? '').replace(/"/g, '""')}"`).join(','))
    .join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToExcel(
  filename: string,
  sheetName: string,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  title: string,
  userName: string,
  role: string,
  appliedFilters?: string
) {
  const wb = XLSX.utils.book_new();
  const dateStr = format(new Date(), 'PPP p');
  const roleDisplay = role ? role.split('_').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') : 'User';

  const exportData: any[][] = [
    ['Two Brothers Food Complex P.L.C'],
    ['2BF Factory ERP — Operational & Executive Report'],
    [],
    ['Report Title', title],
    ['Generated Date', dateStr],
    ['Generated By', `${userName} (${roleDisplay})`],
  ];

  if (appliedFilters) {
    exportData.push(['Applied Filters', appliedFilters]);
  }

  exportData.push([], headers, ...rows);

  const ws = XLSX.utils.aoa_to_sheet(exportData);

  // Column width estimates
  const colWidths = headers.map((h) => ({ wch: Math.max(16, h.length + 4) }));
  ws['!cols'] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, sheetName.substring(0, 31));
  XLSX.writeFile(wb, filename);
}

export function exportToPDF(
  filename: string,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  title: string,
  userName: string,
  role: string,
  appliedFilters?: string
) {
  const orientation = headers.length > 6 ? 'landscape' : 'portrait';
  const doc = new jsPDF(orientation);
  const dateStr = format(new Date(), 'PPP p');
  const roleDisplay = role ? role.split('_').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') : 'User';
  const pageWidth = doc.internal.pageSize.width;

  // ── Header ──
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text('Two Brothers Food Complex P.L.C', 14, 18);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(title, 14, 25);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Generated: ${dateStr}  |  By: ${userName} (${roleDisplay})`, 14, 32);

  let tableStartY = 38;
  if (appliedFilters) {
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(`Filters: ${appliedFilters}`, 14, 37);
    tableStartY = 43;
  }

  // ── Separator Line ──
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, tableStartY - 3, pageWidth - 14, tableStartY - 3);

  // ── Table ──
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: tableStartY,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2.5 },
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 14, right: 14 },
  });

  // ── Footer ──
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.setFont('helvetica', 'normal');
    doc.text('Two Brothers Food Complex P.L.C © 2026 — Factory ERP — Confidential', 14, doc.internal.pageSize.height - 8);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 8);
  }

  doc.save(filename);
}
